OBEX : Handle Illegal Argument Exception
Use case:
1. Reboot the DUT
2. Turn ON BT
3. Try to send file over BT from BT remote
4. wait for incoming file request

Failure:
OPP RX is failing because incoming file request
popup is not coming on UI.

Root cause:
Crash in com.android.bluetooth.

java.lang.IllegalArgumentException: Invalid Header Identifier
 at javax.obex.HeaderSet.setHeader(HeaderSet.java:495)
 javax.obex.ObexHelper.updateHeaderSet(ObexHelper.java:295)
 at javax.obex.ServerOperation.updateRequestHeaders(
    ServerOperation.java:288)

Fix:
Do proper masking of headerArray to calculate the length properly
in uint16.

CRs-Fixed: 2001034
Change-Id: I0d3a9e9939ebe3fbf74c0915c38c0f6532f877a0